import { pool, tx } from '../db.js';
import { config } from '../config.js';
import { validateTelegramInitData } from '../services/telegram.js';
import { createOrRefreshUser, getSessionPayload } from '../services/session.js';
import { placeBet } from '../services/game.js';
import { createInvoice } from '../services/payment.js';
import { keyFrom, findIdempotency, saveIdempotency } from '../middleware/idempotency.js';
import { HttpError } from '../utils/http.js';
import { formatUnits } from '../utils/money.js';
export async function telegramAuth(req,res){const initData=req.body?.initData||req.get('X-Telegram-Init-Data')||'';const tgUser=validateTelegramInitData(initData);const created=await createOrRefreshUser(tgUser);res.cookie('tuff_session',created.token,{httpOnly:true,secure:config.env==='production',sameSite:'lax',path:'/',expires:created.expires});const c=await pool.connect();try{res.json(await getSessionPayload(c,created.user.id))}finally{c.release()}}
export async function me(req,res){const c=await pool.connect();try{res.json(await getSessionPayload(c,req.userId))}finally{c.release()}}
export async function launch(req,res){const game=(await pool.query(`SELECT code,name,provider,launch_mode FROM games WHERE code=$1 AND enabled=true`,[req.body.gameId])).rows[0];if(!game)throw new HttpError(404,'Game not found');res.json({gameId:game.code,name:game.name,mode:game.launch_mode,launchUrl:null});}
export async function bet(req,res){const result=await placeBet(req.userId,req.body,keyFrom(req));res.json(result)}
export async function invoice(req,res){const result=await createInvoice(req.userId,req.body,keyFrom(req));res.status(201).json(result)}
export async function dailyBonus(req,res){const key=keyFrom(req);const result=await tx(async c=>{const old=await findIdempotency(c,req.userId,'bonus.daily',key);if(old)return old.response_body;const last=(await c.query(`SELECT claimed_at FROM bonuses WHERE user_id=$1 AND type='daily' ORDER BY claimed_at DESC LIMIT 1 FOR UPDATE`,[req.userId])).rows[0];if(last&&Date.now()-new Date(last.claimed_at).getTime()<86400000)throw new HttpError(409,'Daily bonus already claimed');const wallet=(await c.query(`SELECT * FROM wallets WHERE user_id=$1 AND currency=$2 FOR UPDATE`,[req.userId,config.currency])).rows[0];const amount=config.testMode?1000000n:0n;if(!config.testMode)throw new HttpError(503,'Production bonus rules are not configured');const before=BigInt(wallet.balance_minor);const bonus=(await c.query(`INSERT INTO bonuses(user_id,type,currency,amount_minor,status,claimed_at) VALUES($1,'daily',$2,$3,'credited',now()) RETURNING id`,[req.userId,config.currency,amount.toString()])).rows[0];await c.query(`UPDATE wallets SET balance_minor=balance_minor+$1,updated_at=now() WHERE id=$2`,[amount.toString(),wallet.id]);await c.query(`INSERT INTO transactions(user_id,wallet_id,type,currency,amount_minor,balance_before_minor,balance_after_minor,reference_type,reference_id) VALUES($1,$2,'bonus',$3,$4,$5,$6,'bonus',$7)`,[req.userId,wallet.id,config.currency,amount.toString(),before.toString(),(before+amount).toString(),bonus.id]);const body={message:`Bonus credited: ${formatUnits(amount)} ${config.currency}`};await saveIdempotency(c,req.userId,'bonus.daily',key,200,body);return body;});res.json(result)}
export async function claimMission(req,res){const key=keyFrom(req);const result=await tx(async c=>{const old=await findIdempotency(c,req.userId,'mission.claim',key);if(old)return old.response_body;const mission=(await c.query(`SELECT um.*,m.reward_minor,m.code FROM user_missions um JOIN missions m ON m.code=um.mission_code WHERE um.user_id=$1 AND um.status='active' ORDER BY um.created_at LIMIT 1 FOR UPDATE`,[req.userId])).rows[0];if(!mission)throw new HttpError(409,'No active mission');const bets=Number((await c.query(`SELECT count(*) count FROM bets WHERE user_id=$1`,[req.userId])).rows[0].count);if(bets<1)throw new HttpError(409,'Mission condition is not completed');const wallet=(await c.query(`SELECT * FROM wallets WHERE user_id=$1 AND currency=$2 FOR UPDATE`,[req.userId,config.currency])).rows[0];const amount=BigInt(mission.reward_minor),before=BigInt(wallet.balance_minor);await c.query(`UPDATE wallets SET balance_minor=balance_minor+$1,updated_at=now() WHERE id=$2`,[amount.toString(),wallet.id]);await c.query(`UPDATE user_missions SET status='claimed',claimed_at=now() WHERE id=$1`,[mission.id]);await c.query(`INSERT INTO transactions(user_id,wallet_id,type,currency,amount_minor,balance_before_minor,balance_after_minor,reference_type,reference_id) VALUES($1,$2,'bonus',$3,$4,$5,$6,'mission',$7)`,[req.userId,wallet.id,config.currency,amount.toString(),before.toString(),(before+amount).toString(),mission.id]);const body={message:`Mission reward: ${formatUnits(amount)} ${config.currency}`};await saveIdempotency(c,req.userId,'mission.claim',key,200,body);return body;});res.json(result)}
