import crypto from 'node:crypto';
import { tx } from '../db.js';
import { config } from '../config.js';
import { parseUnits, formatUnits } from '../utils/money.js';
import { HttpError } from '../utils/http.js';
import { paymentAdapter } from './payments/index.js';
import { findIdempotency, saveIdempotency } from '../middleware/idempotency.js';
export async function createInvoice(userId,input,key){if(input.currency!==config.currency)throw new HttpError(400,'Unsupported currency');if(!config.paymentAllowedAssets.includes(input.asset))throw new HttpError(400,'Unsupported asset/network');const amount=parseUnits(input.amount);if(amount<=0n)throw new HttpError(400,'Invalid amount');return tx(async c=>{const old=await findIdempotency(c,userId,'payment.invoice',key);if(old)return old.response_body;const id=crypto.randomUUID();const [asset,network]=input.asset.split('_');const payment=(await c.query(`INSERT INTO payments(id,user_id,provider,method,asset,network,currency,amount_minor,status,idempotency_key) VALUES($1,$2,$3,'crypto',$4,$5,$6,$7,'created',$8) RETURNING *`,[id,userId,config.paymentProvider,asset,network,config.currency,amount.toString(),key])).rows[0];const provider=await paymentAdapter().createInvoice(payment);await c.query(`UPDATE payments SET external_id=$1,status=$2,provider_payload=$3,updated_at=now() WHERE id=$4`,[provider.externalId,provider.status||'pending',provider,id]);const body={id,externalId:provider.externalId,status:provider.status||'pending',url:provider.url||null,qrUrl:provider.qrUrl||null,amount:formatUnits(amount),asset,network};await saveIdempotency(c,userId,'payment.invoice',key,201,body);return body;});}
export async function processWebhook(raw,headers){const event=paymentAdapter().verifyAndNormalizeWebhook(raw,headers);return tx(async c=>{const payment=(await c.query(`SELECT * FROM payments WHERE external_id=$1 FOR UPDATE`,[event.externalId])).rows[0];if(!payment)throw new HttpError(404,'Payment not found');if(payment.status==='paid')return {ok:true,duplicate:true};if(event.status!=='paid') {await c.query(`UPDATE payments SET status=$1,updated_at=now() WHERE id=$2`,[event.status,payment.id]);return {ok:true,credited:false};}if(event.asset!==payment.asset||event.network!==payment.network)throw new HttpError(400,'Asset or network mismatch');if(parseUnits(event.amount)!==BigInt(payment.amount_minor))throw new HttpError(400,'Amount mismatch');const wallet=(await c.query(`SELECT * FROM wallets WHERE user_id=$1 AND currency=$2 FOR UPDATE`,[payment.user_id,payment.currency])).rows[0];const before=BigInt(wallet.balance_minor),amount=BigInt(payment.amount_minor);await c.query(`UPDATE wallets SET balance_minor=balance_minor+$1,updated_at=now() WHERE id=$2`,[amount.toString(),wallet.id]);await c.query(`INSERT INTO transactions(user_id,wallet_id,type,currency,amount_minor,balance_before_minor,balance_after_minor,reference_type,reference_id,metadata) VALUES($1,$2,'deposit',$3,$4,$5,$6,'payment',$7,$8)`,[payment.user_id,wallet.id,payment.currency,amount.toString(),before.toString(),(before+amount).toString(),payment.id,{eventId:event.eventId}]);await c.query(`UPDATE payments SET status='paid',paid_at=now(),webhook_event_id=$1,updated_at=now() WHERE id=$2`,[event.eventId,payment.id]);return {ok:true,credited:true};});}
