import { Router } from 'express';
import { z } from 'zod';
import { asyncRoute, HttpError } from '../utils/http.js';
import { requireAuth } from '../middleware/auth.js';
import * as c from '../controllers/api.js';
import { config } from '../config.js';
const r=Router();
const validate=schema=>(req,res,next)=>{const out=schema.safeParse(req.body);if(!out.success)return next(new HttpError(400,out.error.issues.map(x=>x.message).join(', '),'VALIDATION_ERROR'));req.body=out.data;next()};
const authSchema=z.object({initData:z.string().optional(),mode:z.enum(['login','register']).optional()});
const gameSchema=z.object({gameId:z.string().min(1).max(80)});
const betSchema=z.object({gameId:z.string().min(1).max(80),amount:z.union([z.string(),z.number()]),currency:z.literal(config.currency)});
const invoiceSchema=z.object({amount:z.union([z.string(),z.number()]),currency:z.literal(config.currency),method:z.literal('crypto').optional().default('crypto'),asset:z.enum(config.paymentAllowedAssets)});
r.post('/miniapp/session',validate(authSchema),asyncRoute(c.telegramAuth));r.post('/auth/telegram',validate(authSchema),asyncRoute(c.telegramAuth));r.get('/me',requireAuth,asyncRoute(c.me));r.post('/games/launch',requireAuth,validate(gameSchema),asyncRoute(c.launch));r.post('/games/bet',requireAuth,validate(betSchema),asyncRoute(c.bet));r.post('/payments/invoices',requireAuth,validate(invoiceSchema),asyncRoute(c.invoice));r.post('/bonuses/daily',requireAuth,asyncRoute(c.dailyBonus));r.post('/missions/current/claim',requireAuth,asyncRoute(c.claimMission));export default r;
